### ISSUE TITLE
مشکل نسخه مک

### ISSUE THREAD

**Issue by nirweb-ir** [MoKhajavi75/iOS_Development_Certificates#46]
سلام و خسته نباشید
متاسفانه سیستمی که من دارم نهایتا نسخه 12.7 مک را میتونم نصب داشته باشم (الان 12.6.4 هست ) ولی روش جدید شما ( سیب اپ ) فایلش در نسخه های 13 و بالاتر قابل اجرا هست.
با توجه به تمام شدن لایسنس (روش قدیمی )آیا راهکاری وجود دارد که در نسخه زیر 13 بتونم استفاده کنم ؟

**Comment by MoKhajavi75** [comment]
@mahadshahib

**Comment by mahadshahib** [comment]
@nirweb-ir خیر متاسفانه
