### ISSUE TITLE
دستزسی به فایل ها 

### ISSUE THREAD

**Issue by saeeddastras** [MoKhajavi75/iOS_Development_Certificates#48]
اگر امکانش هست فایل های  p12 و .mobileprovision رو برای دانلود آ\لود کنید که بتونیم استفاده کنیم 
ممنون 
و اگر امکانش نیست لطفا راهنمایی کنید که چطور میتونم به این فایل ها دسترسی داشته باشم

**Comment by MoKhajavi75** [comment]
@mahadshahib

**Comment by mahadshahib** [comment]
فعلا امکانش نیست.
